
window.onload = function(){
  var dash = new Dashboard();
}

function Dashboard(){
  this.devices = null;
  this.manager_hostname = location.hostname;
  this.manager_port = location.port;
  
  this.main_elem = document.getElementById('apps');
  this.devlist_elem = document.getElementById('dev_list');
  this.dbg_elem = document.getElementById('debug');
  
  this.dbg(this.manager_hostname);
  this.dbg(this.manager_port);
  this.dbg('Dash created');
  this.update();
}

Dashboard.prototype.dbg = function(msg) {
  //
  // print debug message in the debug div
  //
  this.dbg_elem.innerHTML = msg + '<br>' + this.dbg_elem.innerHTML;
}

//get list of devices
Dashboard.prototype.update = function() {
  //
  // Update the list of devices
  //
  var http = new XMLHttpRequest();
  var this_dash = this;
  http.open("GET","/?action=list" ,false);
  http.onreadystatechange=function() {
    if (http.readyState==4 && http.status == 200) {
      this_dash.devices = JSON.parse(http.responseText);
      this_dash.devlist_elem.innerHTML = '';
      //for each device build a bar in the GUI
      for (devuuid in this_dash.devices) {
        var dev_button = document.createElement("button");
        dev_button.type = 'button';
        dev_button.innerHTML = 'launch';
        // "evaluate" uuid right now
        dev_button.onclick = (function(u){
          return function(){
            this_dash.addapp(u);
          }
        })(devuuid);
        var dev_div = document.createElement("div");
        dev_div.setAttribute('class','app_listitem');
        var dev_descr = this_dash.devices[devuuid].name + ": " +
                        this_dash.devices[devuuid].status;
        
        dev_div.appendChild(dev_button);
        dev_div.appendChild(document.createTextNode(dev_descr));
        this_dash.devlist_elem.appendChild(dev_div);
      }
    }
  };
  http.send();
}
Dashboard.prototype.addapp = function(uuid) {
  //
  // Launches App
  // uuid: the uuid of the device associated with the app
  //
  // TODO: make sure an app window doesn't already exist
  // TODO: keep track of app windows, right now it just fires-and-forgets
  var this_dash = this;
  var http = new XMLHttpRequest();
  
  this.dbg ('adding app...');
  
  http.open("GET","/?action=forward&cmd=getCode&uuid="+uuid);
  http.onreadystatechange=function(){
    if (http.readyState==4 && http.status == 200) {
      App = getApp(http.responseText);
      //now make a div for the app to live in.
      var app_element = document.createElement('div');
      this_dash.main_elem.appendChild(app_element);
      app_element.setAttribute("class","app_container");
      // now hand the div to the app.
      var this_app = new App(app_element,uuid,this_dash);
      this_app.start();
    }
  }
  http.send();
}
Dashboard.prototype.stop = function(uuid) {
  //
  // Calls the apps stop method then tears down the HTML div that contained
  // the app associated with the device with uuid uuid.
  //
  
  // TODO: STOP the app 
  this.dbg('stop called on: ' + this.devices[uuid].name +
           "; stop unimplemented");
}
Dashboard.prototype.login = function() {
  //
  // Does login stuff
  //
  
  //todo implement
  this.dbg('login unimplemented');
}
Dashboard.prototype.logout = function() {
  //
  // Does logout stuff
  //
  
  //todo implement
  this.dbg('logout unimplemented');
}
Dashboard.prototype.loadScript = function(scriptSrc,callback) {
  //
  // Loads a script dynamically.
  // scriptSrc: a string containing the source of the script
  // callback: a callback function called when the script has loaded
  //
  var oHead = document.getElementsByTagName('head');
  var oScript = document.createElement('script');
  oScript.type = 'text/javascript';
  oScript.src = sScriptSrc;
  if (callback) {
    oScript.onload = callback;
  }
  oHead.appendChild(oScript);
}

function getApp(appCodeText){
  //
  // Evaluates the input code (as string) and returns the object App
  // generated by the code.
  //
  eval(appCodeText);
  return App;
}
